
services:
  db:
    image: postgres:15
    container_name: postgres_tokyo
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tokyo_models
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_tokyo
    restart: unless-stopped
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tokyo_models
    ports:
      - "3001:3001"
    depends_on:
      - db
#    volumes:
#      - /app/node_modules
    command: yarn run dev

volumes:
  pgdata:
